### ISSUE TITLE
Smazat zbytečný test

### ISSUE THREAD

**Issue by ashhanai** [Bachtanek/GitHub_Learning#21]
Megnu ti to a pak si to nekdy smaz. Dam ti to do issues.

_Originally posted by @ashhanai in https://github.com/Bachtanek/GitHub_Learning/pull/19#discussion_r549006713_

**Comment by ashhabami** [comment]
Ten test byl napsaný špatně, myslel jsem ho jinak, mergnul jsem si lokalně ty testy do CryptoPrice feature, takže pushnu opravenou verzi těch testů tam.
